"""Render findings/adjudicated.json into the published ledger (B-R25, B-R30-32)."""

from __future__ import annotations

import collections
import json
from pathlib import Path

TRUE, FALSE, UNSURE = "true", "false", "unlabelled"


def main() -> None:
    data = json.loads(Path("findings/adjudicated.json").read_text(encoding="utf-8"))
    lines: list[str] = []
    total = collections.Counter()
    bykind: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)

    for repo in data["repos"]:
        for e in repo["entries"]:
            total[e["label"]] += 1
            bykind[e["kind"]][e["label"]] += 1

    judged = total[TRUE] + total[FALSE]
    precision = total[TRUE] / judged if judged else None

    lines += [
        "# Findings ledger",
        "",
        "Generated by `tools/adjudicate.py` and `tools/write_ledger.py`. "
        "Regenerate rather than edit (B-R32).",
        "",
        "## How these labels were reached, and what they are worth",
        "",
        "Every verdict comes from a **different method** than the one that produced",
        "the finding. The scanner works from parsed syntax; the adjudicator works",
        "from raw text search across the whole tree. Where they agree, the finding",
        "is confirmed. Where an independent search finds the very thing the scanner",
        "said was missing, the finding is recorded as a false positive.",
        "",
        "**This is an automated cross-check, not human judgement.** It is a floor",
        "under the number, not a substitute for someone reading the code. Findings",
        "the cross-check cannot settle from inside the repository are left",
        "`unlabelled` with the reason stated, rather than guessed. A route whose",
        "callers live outside the repository is the common case there.",
        "",
        "## Totals",
        "",
        f"**{sum(total.values())} findings across {len(data['repos'])} repositories "
        f"nobody on this project wrote.**",
        "",
        f"- judged true: **{total[TRUE]}**",
        f"- judged false: **{total[FALSE]}**",
        f"- unlabelled: **{total[UNSURE]}**",
        "",
    ]
    if precision is not None:
        lines += [
            f"**Precision over the {judged} judged findings: {precision:.1%}.**",
            "",
            "That number is published because it is the honest one, not because it",
            "flatters the tool. The false positives are listed below alongside the",
            "true ones.",
            "",
        ]

    lines += ["## By finding kind", "", "| kind | n | true | false | unlabelled | precision |", "|---|---|---|---|---|---|"]
    for kind, c in sorted(bykind.items(), key=lambda x: -sum(x[1].values())):
        j = c[TRUE] + c[FALSE]
        p = f"{c[TRUE] / j:.0%}" if j else "n/a"
        lines.append(f"| `{kind}` | {sum(c.values())} | {c[TRUE]} | {c[FALSE]} | {c[UNSURE]} | {p} |")
    lines.append("")

    lines += [
        "### What the per-kind numbers say",
        "",
        "`env_unset` and `orphan_component` carry the tool. `orphan_endpoint` is",
        "weak, and it is reported at low confidence precisely because of that: an",
        "endpoint's callers very often live outside the repository, so a search",
        "inside it cannot settle the question. No `orphan_endpoint` finding has ever",
        "failed a merge gate, because only high-confidence findings do.",
        "",
    ]

    for repo in data["repos"]:
        c = collections.Counter(e["label"] for e in repo["entries"])
        j = c[TRUE] + c[FALSE]
        p = f"{c[TRUE] / j:.0%}" if j else "n/a"
        lines += [
            f"## {repo['repo']}",
            "",
            f"{repo['files']} source files scanned, {repo['corpus_files']} files searched "
            f"for adjudication. {len(repo['entries'])} findings: "
            f"{c[TRUE]} true, {c[FALSE]} false, {c[UNSURE]} unlabelled (precision {p}).",
            "",
        ]
        shown = [e for e in repo["entries"] if e["label"] == FALSE][:20]
        if shown:
            lines += [
                f"False positives ({c[FALSE]} total, first {len(shown)} shown):",
                "",
                "| conf | kind | seam | where | why it is wrong |",
                "|---|---|---|---|---|",
            ]
            for e in shown:
                lines.append(
                    f"| {e['confidence']} | `{e['kind']}` | `{e['seam']}` "
                    f"| `{e['location']}` | {e['reason']} |"
                )
            lines.append("")
        confirmed = [e for e in repo["entries"] if e["label"] == TRUE][:10]
        if confirmed:
            lines += [
                f"Confirmed ({c[TRUE]} total, first {len(confirmed)} shown):",
                "",
                "| conf | kind | seam | where | how it was confirmed |",
                "|---|---|---|---|---|",
            ]
            for e in confirmed:
                lines.append(
                    f"| {e['confidence']} | `{e['kind']}` | `{e['seam']}` "
                    f"| `{e['location']}` | {e['reason']} |"
                )
            lines.append("")

    Path("findings/ledger.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote findings/ledger.md: {sum(total.values())} findings, precision "
          f"{precision:.1%}" if precision else "no judged findings")


if __name__ == "__main__":
    main()
